### PR TITLE
[JB][OPS-6111] Update MODS tps-backend request

### PR DESCRIPTION
**Pull request by barnesjake**

### CODE REVIEW

**Comment by barnesjake** [comment]
test this please

**Comment by barnesjake** [comment]
test this please

**Comment by barnesjake** [comment]
test this please

**Comment by barnesjake** [comment]
test this please

**Review by alex-newby-hmrc — APPROVED** [review]

**Comment by barnesjake** [comment]
test this please

**Comment by barnesjake** [comment]
test this please

**Pull request merged**
